baseurl = "dannyp.github.io"
title = "dannypallotta"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Danny Pallotta"
  info = "Data Engineer and Coffee Drinker"
  description = "Danny's personal website"
  keywords = "blog,data,developer,personal"
  avatarurl = "images/avatar.svg"
  #gravatar = "danny.pallotta@gmail.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  dateFormat = "January, 2006"

  since = 2020

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

#[taxonomies]
#  category = "categories"
  series = "series"
#  tag = "tags"
#  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/dannyp/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/dannypallotta/"
[[params.social]]
  name = "Chess"
  icon = "fa fa-handshake-o fa-2x"
  weight = 3
  url = "https://www.chess.com/member/dfpl/"

# Menu links
[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "Experience"
  weight = 2
  url = "experience/"